// <auto-generated />
using System;
using App.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251212093527_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("App.Domain.Entities.AnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChoiceQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MultipleChoiceQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChoiceQuestionId");

                    b.HasIndex("MultipleChoiceQuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8769cd44-270e-47e7-8f90-5d22f6e8d5df"),
                            IsCorrect = true,
                            QuestionId = new Guid("f3e06a66-0c62-4d5a-9216-c29bdcb6c878"),
                            Text = "Место для хранения значения"
                        },
                        new
                        {
                            Id = new Guid("d4578eb2-70cb-4b05-b765-6bec602d65c7"),
                            IsCorrect = false,
                            QuestionId = new Guid("f3e06a66-0c62-4d5a-9216-c29bdcb6c878"),
                            Text = "Тип данных"
                        },
                        new
                        {
                            Id = new Guid("d83f9f95-86f2-478e-b2a4-6ee12b0da1a9"),
                            IsCorrect = true,
                            QuestionId = new Guid("60d1b826-13af-41ed-95b6-195ebe4add69"),
                            Text = "Повторяющееся выполнение блока кода"
                        },
                        new
                        {
                            Id = new Guid("9031c6d1-df26-4bb4-84f6-28418df8a37c"),
                            IsCorrect = false,
                            QuestionId = new Guid("60d1b826-13af-41ed-95b6-195ebe4add69"),
                            Text = "Класс в C#"
                        });
                });

            modelBuilder.Entity("App.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasDiscriminator<string>("QuestionType").HasValue("Question");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("App.Domain.Entities.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6ff30c7f-f6e4-4e79-ba9a-edff4b430c68"),
                            Code = "QZ001",
                            CreatedAt = new DateTime(2025, 12, 12, 9, 35, 24, 163, DateTimeKind.Utc).AddTicks(8035),
                            Title = "C# Basics"
                        });
                });

            modelBuilder.Entity("App.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("QuestionTag", b =>
                {
                    b.Property<Guid>("QuestionsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("TEXT");

                    b.HasKey("QuestionsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("QuestionTag");
                });

            modelBuilder.Entity("App.Domain.Entities.ChoiceQuestion", b =>
                {
                    b.HasBaseType("App.Domain.Entities.Question");

                    b.Property<bool>("Multiple")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Choice");
                });

            modelBuilder.Entity("App.Domain.Entities.MultipleChoiceQuestion", b =>
                {
                    b.HasBaseType("App.Domain.Entities.Question");

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("MultipleChoice");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3e06a66-0c62-4d5a-9216-c29bdcb6c878"),
                            Order = 1,
                            QuestionType = "MultipleChoice",
                            QuizId = new Guid("6ff30c7f-f6e4-4e79-ba9a-edff4b430c68"),
                            Text = "Что такое переменная?",
                            CorrectIndex = 1
                        },
                        new
                        {
                            Id = new Guid("60d1b826-13af-41ed-95b6-195ebe4add69"),
                            Order = 2,
                            QuestionType = "MultipleChoice",
                            QuizId = new Guid("6ff30c7f-f6e4-4e79-ba9a-edff4b430c68"),
                            Text = "Что такое цикл?",
                            CorrectIndex = 0
                        });
                });

            modelBuilder.Entity("App.Domain.Entities.AnswerOption", b =>
                {
                    b.HasOne("App.Domain.Entities.ChoiceQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("ChoiceQuestionId");

                    b.HasOne("App.Domain.Entities.MultipleChoiceQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("MultipleChoiceQuestionId");

                    b.HasOne("App.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("App.Domain.Entities.Question", b =>
                {
                    b.HasOne("App.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuestionTag", b =>
                {
                    b.HasOne("App.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Entities.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("App.Domain.Entities.ChoiceQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("App.Domain.Entities.MultipleChoiceQuestion", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
