// <auto-generated />
using System;
using App.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215135400_AddTimeLimit")]
    partial class AddTimeLimit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("App.Domain.Entities.AnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChoiceQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MultipleChoiceQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChoiceQuestionId");

                    b.HasIndex("MultipleChoiceQuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2585133-6c48-4a4b-931a-4452a72fa089"),
                            IsCorrect = true,
                            QuestionId = new Guid("ad7f5454-be71-4fbd-8478-ba49407a30b6"),
                            Text = "Место для хранения значения"
                        },
                        new
                        {
                            Id = new Guid("9576aa35-31d7-4d24-8478-50ecbd9c14f5"),
                            IsCorrect = false,
                            QuestionId = new Guid("ad7f5454-be71-4fbd-8478-ba49407a30b6"),
                            Text = "Тип данных"
                        },
                        new
                        {
                            Id = new Guid("af714130-220e-4060-82a6-f6a913c97417"),
                            IsCorrect = true,
                            QuestionId = new Guid("a5ab5d08-9f7f-42ea-a98d-5c29242b17e0"),
                            Text = "Повторяющееся выполнение блока кода"
                        },
                        new
                        {
                            Id = new Guid("3f33e92e-cb63-4cc4-b0e2-238312717468"),
                            IsCorrect = false,
                            QuestionId = new Guid("a5ab5d08-9f7f-42ea-a98d-5c29242b17e0"),
                            Text = "Класс в C#"
                        });
                });

            modelBuilder.Entity("App.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeLimitSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasDiscriminator<string>("QuestionType").HasValue("Question");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("App.Domain.Entities.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("224c892c-4463-448a-918b-6eae1aa5968f"),
                            Code = "QZ001",
                            CreatedAt = new DateTime(2025, 12, 15, 13, 53, 59, 329, DateTimeKind.Utc).AddTicks(3808),
                            Title = "C# Basics"
                        });
                });

            modelBuilder.Entity("App.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("QuestionTag", b =>
                {
                    b.Property<Guid>("QuestionsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("TEXT");

                    b.HasKey("QuestionsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("QuestionTag");
                });

            modelBuilder.Entity("App.Domain.Entities.ChoiceQuestion", b =>
                {
                    b.HasBaseType("App.Domain.Entities.Question");

                    b.Property<bool>("Multiple")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Choice");
                });

            modelBuilder.Entity("App.Domain.Entities.MultipleChoiceQuestion", b =>
                {
                    b.HasBaseType("App.Domain.Entities.Question");

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("MultipleChoice");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad7f5454-be71-4fbd-8478-ba49407a30b6"),
                            Order = 1,
                            QuestionType = "MultipleChoice",
                            QuizId = new Guid("224c892c-4463-448a-918b-6eae1aa5968f"),
                            Text = "Что такое переменная?",
                            TimeLimitSeconds = 15,
                            CorrectIndex = 1
                        },
                        new
                        {
                            Id = new Guid("a5ab5d08-9f7f-42ea-a98d-5c29242b17e0"),
                            Order = 2,
                            QuestionType = "MultipleChoice",
                            QuizId = new Guid("224c892c-4463-448a-918b-6eae1aa5968f"),
                            Text = "Что такое цикл?",
                            TimeLimitSeconds = 15,
                            CorrectIndex = 0
                        });
                });

            modelBuilder.Entity("App.Domain.Entities.AnswerOption", b =>
                {
                    b.HasOne("App.Domain.Entities.ChoiceQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("ChoiceQuestionId");

                    b.HasOne("App.Domain.Entities.MultipleChoiceQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("MultipleChoiceQuestionId");

                    b.HasOne("App.Domain.Entities.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("App.Domain.Entities.Question", b =>
                {
                    b.HasOne("App.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuestionTag", b =>
                {
                    b.HasOne("App.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Entities.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("App.Domain.Entities.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("App.Domain.Entities.ChoiceQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("App.Domain.Entities.MultipleChoiceQuestion", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
